# Generated by Django 5.2.10 on 2026-01-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id_alter_order_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_name',
            new_name='name',
        ),
    ]
